server.port=8080
spring.application.name=api-gateway

registry.service.url=${REGISTRY_URL:http://localhost:8082}
monitoring.service.url=${MONITORING_URL:http://localhost:8081}
notification.service.url=${NOTIFICATION_URL:http://localhost:8084}
